export const chatCopy = {
  en: {
    title: 'Chat with the studio',
    launcher: 'Live chat',
    close: 'Close chat',
    online: 'The studio is online',
    offline: 'Leave us a message',
    welcome: 'A question, an idea, a custom print?',
    intro: 'Talk directly with GrandXStudio. How can we help?',
    away: 'We’re away right now. Leave a message and return to this chat for our reply.',
    name: 'Your name',
    email: 'Email',
    message: 'Your message',
    placeholder: 'Tell us what you have in mind…',
    send: 'Send message',
    sending: 'Sending…',
    privacy: 'I agree to the privacy policy.',
    privacyLink: 'Privacy policy',
    returnNotice:
      'Replies appear here. Return in this browser within 30 days. No email notification is sent.',
    loading: 'Opening your conversation…',
    earlier: 'Load earlier messages',
    resolved: 'This conversation is resolved. Send a message to reopen it.',
    unavailable: 'Chat is currently unavailable.',
    contact: 'Use the contact form',
    error: 'Could not connect. Your message has not been cleared. Please try again.',
    connection: 'Connection interrupted. Reconnecting…',
    retry: 'Try again',
    you: 'You',
    studio: 'GrandXStudio',
    newReply: 'New reply',
  },
  mk: {
    title: 'Разговор со студиото',
    launcher: 'Разговор во живо',
    close: 'Затвори разговор',
    online: 'Студиото е онлајн',
    offline: 'Оставете ни порака',
    welcome: 'Прашање, идеја, печатење по мерка?',
    intro: 'Разговарајте директно со GrandXStudio. Како можеме да помогнеме?',
    away: 'Во моментов сме отсутни. Оставете порака и вратете се во разговорот за нашиот одговор.',
    name: 'Вашето име',
    email: 'Е-пошта',
    message: 'Вашата порака',
    placeholder: 'Кажете ни што замислувате…',
    send: 'Испрати порака',
    sending: 'Се испраќа…',
    privacy: 'Се согласувам со политиката за приватност.',
    privacyLink: 'Политика за приватност',
    returnNotice:
      'Одговорите се прикажуваат тука. Вратете се во истиот прелистувач во рок од 30 дена. Не се испраќа известување по е-пошта.',
    loading: 'Се отвора разговорот…',
    earlier: 'Вчитај претходни пораки',
    resolved: 'Разговорот е завршен. Испратете порака за повторно да го отворите.',
    unavailable: 'Разговорот моментално не е достапен.',
    contact: 'Користете ја контакт-формата',
    error: 'Не успеавме да се поврземе. Пораката е зачувана во полето. Обидете се повторно.',
    connection: 'Врската е прекината. Повторно се поврзуваме…',
    retry: 'Обиди се повторно',
    you: 'Вие',
    studio: 'GrandXStudio',
    newReply: 'Нов одговор',
  },
};
export type ChatCopy = typeof chatCopy.en;
